// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameProtocol.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "GameProtocol.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace qiyi {
namespace forever {
namespace master {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* AccountCreateRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AccountCreateRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* AccountCreateResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AccountCreateResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* LoginRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoginRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* LoginResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoginResponse_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Opration_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_GameProtocol_2eproto() {
  protobuf_AddDesc_GameProtocol_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "GameProtocol.proto");
  GOOGLE_CHECK(file != NULL);
  AccountCreateRequest_descriptor_ = file->message_type(0);
  static const int AccountCreateRequest_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountCreateRequest, opt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountCreateRequest, username_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountCreateRequest, password_),
  };
  AccountCreateRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AccountCreateRequest_descriptor_,
      AccountCreateRequest::default_instance_,
      AccountCreateRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountCreateRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountCreateRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AccountCreateRequest));
  AccountCreateResponse_descriptor_ = file->message_type(1);
  static const int AccountCreateResponse_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountCreateResponse, opt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountCreateResponse, errorcode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountCreateResponse, msg_),
  };
  AccountCreateResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AccountCreateResponse_descriptor_,
      AccountCreateResponse::default_instance_,
      AccountCreateResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountCreateResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountCreateResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AccountCreateResponse));
  LoginRequest_descriptor_ = file->message_type(2);
  static const int LoginRequest_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequest, opt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequest, username_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequest, password_),
  };
  LoginRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LoginRequest_descriptor_,
      LoginRequest::default_instance_,
      LoginRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LoginRequest));
  LoginResponse_descriptor_ = file->message_type(3);
  static const int LoginResponse_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResponse, opt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResponse, errorcode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResponse, msg_),
  };
  LoginResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      LoginResponse_descriptor_,
      LoginResponse::default_instance_,
      LoginResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(LoginResponse));
  Opration_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_GameProtocol_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AccountCreateRequest_descriptor_, &AccountCreateRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AccountCreateResponse_descriptor_, &AccountCreateResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LoginRequest_descriptor_, &LoginRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    LoginResponse_descriptor_, &LoginResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_GameProtocol_2eproto() {
  delete AccountCreateRequest::default_instance_;
  delete AccountCreateRequest_reflection_;
  delete AccountCreateResponse::default_instance_;
  delete AccountCreateResponse_reflection_;
  delete LoginRequest::default_instance_;
  delete LoginRequest_reflection_;
  delete LoginResponse::default_instance_;
  delete LoginResponse_reflection_;
}

void protobuf_AddDesc_GameProtocol_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022GameProtocol.proto\022 com.qiyi.forever.m"
    "aster.protobuf\"\202\001\n\024AccountCreateRequest\022"
    "F\n\003opt\030\001 \001(\0162*.com.qiyi.forever.master.p"
    "rotobuf.Opration:\rACCOUNT_CREAT\022\020\n\010usern"
    "ame\030\002 \002(\t\022\020\n\010password\030\003 \002(\t\"\177\n\025AccountCr"
    "eateResponse\022F\n\003opt\030\001 \001(\0162*.com.qiyi.for"
    "ever.master.protobuf.Opration:\rACCOUNT_C"
    "REAT\022\021\n\terrorCode\030\002 \002(\005\022\013\n\003msg\030\003 \002(\t\"r\n\014"
    "LoginRequest\022>\n\003opt\030\001 \001(\0162*.com.qiyi.for"
    "ever.master.protobuf.Opration:\005LOGIN\022\020\n\010"
    "username\030\002 \002(\t\022\020\n\010password\030\003 \002(\t\"o\n\rLogi"
    "nResponse\022>\n\003opt\030\001 \001(\0162*.com.qiyi.foreve"
    "r.master.protobuf.Opration:\005LOGIN\022\021\n\terr"
    "orCode\030\002 \002(\005\022\013\n\003msg\030\003 \002(\t*(\n\010Opration\022\021\n"
    "\rACCOUNT_CREAT\020\001\022\t\n\005LOGIN\020\002B\002H\002", 591);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "GameProtocol.proto", &protobuf_RegisterTypes);
  AccountCreateRequest::default_instance_ = new AccountCreateRequest();
  AccountCreateResponse::default_instance_ = new AccountCreateResponse();
  LoginRequest::default_instance_ = new LoginRequest();
  LoginResponse::default_instance_ = new LoginResponse();
  AccountCreateRequest::default_instance_->InitAsDefaultInstance();
  AccountCreateResponse::default_instance_->InitAsDefaultInstance();
  LoginRequest::default_instance_->InitAsDefaultInstance();
  LoginResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_GameProtocol_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_GameProtocol_2eproto {
  StaticDescriptorInitializer_GameProtocol_2eproto() {
    protobuf_AddDesc_GameProtocol_2eproto();
  }
} static_descriptor_initializer_GameProtocol_2eproto_;
const ::google::protobuf::EnumDescriptor* Opration_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Opration_descriptor_;
}
bool Opration_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int AccountCreateRequest::kOptFieldNumber;
const int AccountCreateRequest::kUsernameFieldNumber;
const int AccountCreateRequest::kPasswordFieldNumber;
#endif  // !_MSC_VER

AccountCreateRequest::AccountCreateRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void AccountCreateRequest::InitAsDefaultInstance() {
}

AccountCreateRequest::AccountCreateRequest(const AccountCreateRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void AccountCreateRequest::SharedCtor() {
  _cached_size_ = 0;
  opt_ = 1;
  username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AccountCreateRequest::~AccountCreateRequest() {
  SharedDtor();
}

void AccountCreateRequest::SharedDtor() {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    delete username_;
  }
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    delete password_;
  }
  if (this != default_instance_) {
  }
}

void AccountCreateRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AccountCreateRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AccountCreateRequest_descriptor_;
}

const AccountCreateRequest& AccountCreateRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GameProtocol_2eproto();
  return *default_instance_;
}

AccountCreateRequest* AccountCreateRequest::default_instance_ = NULL;

AccountCreateRequest* AccountCreateRequest::New() const {
  return new AccountCreateRequest;
}

void AccountCreateRequest::Swap(AccountCreateRequest* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata AccountCreateRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AccountCreateRequest_descriptor_;
  metadata.reflection = AccountCreateRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int AccountCreateResponse::kOptFieldNumber;
const int AccountCreateResponse::kErrorCodeFieldNumber;
const int AccountCreateResponse::kMsgFieldNumber;
#endif  // !_MSC_VER

AccountCreateResponse::AccountCreateResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void AccountCreateResponse::InitAsDefaultInstance() {
}

AccountCreateResponse::AccountCreateResponse(const AccountCreateResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void AccountCreateResponse::SharedCtor() {
  _cached_size_ = 0;
  opt_ = 1;
  errorcode_ = 0;
  msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AccountCreateResponse::~AccountCreateResponse() {
  SharedDtor();
}

void AccountCreateResponse::SharedDtor() {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    delete msg_;
  }
  if (this != default_instance_) {
  }
}

void AccountCreateResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AccountCreateResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AccountCreateResponse_descriptor_;
}

const AccountCreateResponse& AccountCreateResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GameProtocol_2eproto();
  return *default_instance_;
}

AccountCreateResponse* AccountCreateResponse::default_instance_ = NULL;

AccountCreateResponse* AccountCreateResponse::New() const {
  return new AccountCreateResponse;
}

void AccountCreateResponse::Swap(AccountCreateResponse* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata AccountCreateResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AccountCreateResponse_descriptor_;
  metadata.reflection = AccountCreateResponse_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int LoginRequest::kOptFieldNumber;
const int LoginRequest::kUsernameFieldNumber;
const int LoginRequest::kPasswordFieldNumber;
#endif  // !_MSC_VER

LoginRequest::LoginRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void LoginRequest::InitAsDefaultInstance() {
}

LoginRequest::LoginRequest(const LoginRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void LoginRequest::SharedCtor() {
  _cached_size_ = 0;
  opt_ = 2;
  username_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LoginRequest::~LoginRequest() {
  SharedDtor();
}

void LoginRequest::SharedDtor() {
  if (username_ != &::google::protobuf::internal::kEmptyString) {
    delete username_;
  }
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    delete password_;
  }
  if (this != default_instance_) {
  }
}

void LoginRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoginRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoginRequest_descriptor_;
}

const LoginRequest& LoginRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GameProtocol_2eproto();
  return *default_instance_;
}

LoginRequest* LoginRequest::default_instance_ = NULL;

LoginRequest* LoginRequest::New() const {
  return new LoginRequest;
}

void LoginRequest::Swap(LoginRequest* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata LoginRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoginRequest_descriptor_;
  metadata.reflection = LoginRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int LoginResponse::kOptFieldNumber;
const int LoginResponse::kErrorCodeFieldNumber;
const int LoginResponse::kMsgFieldNumber;
#endif  // !_MSC_VER

LoginResponse::LoginResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void LoginResponse::InitAsDefaultInstance() {
}

LoginResponse::LoginResponse(const LoginResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void LoginResponse::SharedCtor() {
  _cached_size_ = 0;
  opt_ = 2;
  errorcode_ = 0;
  msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LoginResponse::~LoginResponse() {
  SharedDtor();
}

void LoginResponse::SharedDtor() {
  if (msg_ != &::google::protobuf::internal::kEmptyString) {
    delete msg_;
  }
  if (this != default_instance_) {
  }
}

void LoginResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoginResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoginResponse_descriptor_;
}

const LoginResponse& LoginResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_GameProtocol_2eproto();
  return *default_instance_;
}

LoginResponse* LoginResponse::default_instance_ = NULL;

LoginResponse* LoginResponse::New() const {
  return new LoginResponse;
}

void LoginResponse::Swap(LoginResponse* other) {
  if (other != this) {
    GetReflection()->Swap(this, other);}
}

::google::protobuf::Metadata LoginResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoginResponse_descriptor_;
  metadata.reflection = LoginResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace master
}  // namespace forever
}  // namespace qiyi
}  // namespace com

// @@protoc_insertion_point(global_scope)
